apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-operator-main
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-operator-main
    app.kubernetes.io/part-of: hypershift-operator
  name: hypershift-operator-main
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: hypershift-operator-main
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hypershift-operator-main
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-operator/hypershift-operator-main@sha256:79fff51c66c89c1c0102995dd4e8d410d3d203350c1a636bb4870aab28580cbf
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
