apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-operator-main
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-operator-main
    app.kubernetes.io/part-of: hypershift-operator
  name: hypershift-operator-main
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: hypershift-operator-main
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hypershift-operator-main
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-operator/hypershift-operator-main@sha256:d80e18073fbe3b57a0ac45f394504df72abd6d67f0e70c0ea1f6e5ede4e5c588
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
