apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-operator-main
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-operator-main
    app.kubernetes.io/part-of: hypershift-operator
  name: hypershift-operator-main82ac
spec:
  port:
    targetPort: 9090
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hypershift-operator-main
    weight: 100
status: {}
